Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -5,18 +5,64 @@ jobs:
       - image: cimg/ruby:3.0.2
     steps:
       - checkout
-      - run: echo "A first hello"
-      - run: sleep 5
-  test:
+      - run: mkdir -p my_workspace
+      - run: echo "Hello World" > my_workspace/echo-output
+      - persist_to_workspace:
+          # Must be an absolute path, or relative path from working_directory
+          root: my_workspace
+          # Must be relative path from root
+          paths:
+            - echo-output      
+  testa:
     docker:
       - image: cimg/ruby:3.0.2
     steps:
-      - checkout
-      - run: echo "A more familiar hi"
-      - run: sleep 5
+      - attach_workspace:
+          # Must be absolute path or relative path from working_directory
+          at: my_workspace
+
+      - run: cat my_workspace/echo-output
+          
+  testb:
+    docker:
+      - image: cimg/ruby:3.0.2
+    steps:
+      - attach_workspace:
+          # Must be absolute path or relative path from working_directory
+          at: my_workspace
+
+      - run: |
+          # this will fail intentionally, we'll use SSH to debug and fix
+          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
+            echo "It worked!";
+          else
+            echo "Nope!"; exit 1
+          fi   
+          
+  deploy:
+    docker:
+      - image: cimg/ruby:3.0.2
+    steps:
+      - attach_workspace:
+          # Must be absolute path or relative path from working_directory
+          at: my_workspace
+
+      - run: |
+          echo "Deploying message!"
+          cat my_workspace/echo-output
+
 workflows:
   version: 2.1
   build_and_test:
     jobs:
       - build
-      - test
+      - testa:
+          requires:
+            - build 
+      - testb:
+          requires:
+            - build 
+      - deploy:
+          requires:
+            - testa
+            - testb
